[project]
name = "task-timer"
version = "1.0.0"
description = "This Task Timer is able to time tasks."
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "rich>=13.9.4",
]

[project.scripts]
task-timer= "task_timer:main"

[tool.uv]
package = true
